import type {
  GetUpdatedEnvFileCaseType,
  GetUpdatedEnvFileParamsType,
  GetUpdatedEnvFileResType,
} from './getUpdatedEnvFile'

export const getUpdatedEnvFileCases: GetUpdatedEnvFileCaseType[] = [
  // ---------- structure / newlines ----------
  {
    index: 0,
    description: 'updates an existing key in place',
    fileContent: 'A=1\nB=2\n',
    params: { updates: { A: '10' } },
    options: {},
    expected: { A: '10', B: '2' },
    expectedFileContent: 'A=10\nB=2\n',
  },
  {
    index: 1,
    description: 'appends a missing key without a blank line',
    fileContent: 'A=1\n',
    params: { updates: { B: '2' } },
    options: {},
    expected: { A: '1', B: '2' },
    expectedFileContent: 'A=1\nB=2\n',
  },
  {
    index: 2,
    description: 'file without trailing newline gets one',
    fileContent: 'A=1',
    params: { updates: { B: '2' } },
    options: {},
    expected: { A: '1', B: '2' },
    expectedFileContent: 'A=1\nB=2\n',
  },
  {
    index: 3,
    description: 'empty file: no leading blank line',
    fileContent: '',
    params: { updates: { B: '2' } },
    options: {},
    expected: { B: '2' },
    expectedFileContent: 'B=2\n',
  },
  {
    index: 4,
    description: 'CRLF newlines are preserved',
    fileContent: 'A=1\r\nB=2\r\n',
    params: { updates: { A: '3', C: '4' } },
    options: {},
    expected: { A: '3', B: '2', C: '4' },
    expectedFileContent: 'A=3\r\nB=2\r\nC=4\r\n',
  },
  {
    index: 5,
    description: 'empty updates leave content unchanged',
    fileContent: 'A=1\n',
    params: { updates: {} },
    options: {},
    expected: { A: '1' },
    expectedFileContent: 'A=1\n',
  },
  {
    index: 6,
    description: 'existing keys keep their position, new keys are appended in order',
    fileContent: 'A=1\nB=2\n',
    params: { updates: { B: '20', C: '30', A: '10' } },
    options: {},
    expected: { A: '10', B: '20', C: '30' },
    expectedFileContent: 'A=10\nB=20\nC=30\n',
  },

  // ---------- line matching ----------
  {
    index: 7,
    description: 'export prefix is preserved',
    fileContent: 'export FOO=1\n',
    params: { updates: { FOO: '2' } },
    options: {},
    expected: { FOO: '2' },
    expectedFileContent: 'export FOO=2\n',
  },
  {
    index: 8,
    description: 'leading whitespace is preserved',
    fileContent: '  A=1\n',
    params: { updates: { A: '2' } },
    options: {},
    expected: { A: '2' },
    expectedFileContent: '  A=2\n',
  },
  {
    index: 9,
    description: 'duplicate assignments are removed, first one is kept',
    fileContent: 'A=1\nB=2\nA=3\n',
    params: { updates: { A: '9' } },
    options: {},
    expected: { A: '9', B: '2' },
    expectedFileContent: 'A=9\nB=2\n',
  },
  {
    index: 10,
    description: 'comments and blank lines are untouched',
    fileContent: '# comment\nA=1\n\nB=2\n',
    params: { updates: { A: '5' } },
    options: {},
    expected: { A: '5', B: '2' },
    expectedFileContent: '# comment\nA=5\n\nB=2\n',
  },
  {
    index: 11,
    description: 'commented-out key is not matched, key is appended instead',
    fileContent: '#A=1\nB=2\n',
    params: { updates: { A: '9' } },
    options: {},
    expected: { B: '2', A: '9' },
    expectedFileContent: '#A=1\nB=2\nA=9\n',
  },
  {
    index: 12,
    description: 'inline comment on a replaced line is dropped (documents current behaviour)',
    fileContent: 'A=1 # note\n',
    params: { updates: { A: '2' } },
    options: {},
    expected: { A: '2' },
    expectedFileContent: 'A=2\n',
  },
  {
    index: 13,
    description: 'prototype names in the file are not treated as update keys',
    fileContent: 'constructor=x\nA=1\n',
    params: { updates: { A: '2' } },
    options: {},
    expected: { constructor: 'x', A: '2' },
    expectedFileContent: 'constructor=x\nA=2\n',
  },

  // ---------- value types and formatting ----------
  {
    index: 14,
    description: 'boolean and number are stringified',
    fileContent: 'A=1\n',
    params: { updates: { DEBUG: true, PORT: 3000 } },
    options: {},
    expected: { A: '1', DEBUG: 'true', PORT: '3000' },
    expectedFileContent: 'A=1\nDEBUG=true\nPORT=3000\n',
  },
  {
    index: 15,
    description: 'plain URL-like value stays unquoted',
    fileContent: '',
    params: { updates: { URL: 'http://localhost:3000/api' } },
    options: {},
    expected: { URL: 'http://localhost:3000/api' },
    expectedFileContent: 'URL=http://localhost:3000/api\n',
  },
  {
    index: 16,
    description: 'value with spaces is double-quoted',
    fileContent: '',
    params: { updates: { GREETING: 'hello world' } },
    options: {},
    expected: { GREETING: 'hello world' },
    expectedFileContent: 'GREETING="hello world"\n',
  },
  {
    index: 17,
    description: 'value with # is quoted so it is not read as a comment',
    fileContent: '',
    params: { updates: { PASS: 'pass#word' } },
    options: {},
    expected: { PASS: 'pass#word' },
    expectedFileContent: 'PASS="pass#word"\n',
  },
  {
    index: 18,
    description: 'empty string becomes ""',
    fileContent: 'EMPTY=old\n',
    params: { updates: { EMPTY: '' } },
    options: {},
    expected: { EMPTY: '' },
    expectedFileContent: 'EMPTY=""\n',
  },
  {
    index: 19,
    description: 'value containing " falls back to single quotes',
    fileContent: '',
    params: { updates: { Q: 'say "hi"' } },
    options: {},
    expected: { Q: 'say "hi"' },
    expectedFileContent: `Q='say "hi"'\n`,
  },
  {
    index: 20,
    description: 'value containing " and \' falls back to backticks',
    fileContent: '',
    params: { updates: { Q: `it's "ok"` } },
    options: {},
    expected: { Q: `it's "ok"` },
    expectedFileContent: 'Q=`it\'s "ok"`\n',
  },
  {
    index: 21,
    description: 'real newline is escaped inside double quotes and round-trips',
    fileContent: '',
    params: { updates: { M: 'line1\nline2' } },
    options: {},
    expected: { M: 'line1\nline2' },
    expectedFileContent: 'M="line1\\nline2"\n',
  },
  {
    index: 22,
    description: 'backslash followed by n round-trips via single quotes',
    fileContent: '',
    params: { updates: { P: 'C:\\new' } },
    options: {},
    expected: { P: 'C:\\new' },
    expectedFileContent: "P='C:\\new'\n",
  },
  {
    index: 29,
    description: 'literal \\n plus single quote falls back to backticks',
    fileContent: '',
    params: { updates: { P: "it's C:\\new" } },
    options: {},
    expected: { P: "it's C:\\new" },
    expectedFileContent: "P=`it's C:\\new`\n",
  },
  {
    index: 30,
    description: 'throws when value has a real newline and a literal \\n (ambiguous)',
    fileContent: 'A=1\n',
    params: { updates: { P: 'a\nb\\nc' } },
    options: {},
    expectedError: 'Value cannot be represented in a .env file',
  },
  {
    index: 31,
    description: 'literal \\n with all three quote types throws',
    fileContent: 'A=1\n',
    params: { updates: { P: '\\n\'"`' } },
    options: {},
    expectedError: 'Value cannot be represented in a .env file',
  },
]
